name: data_inmemory
description: An in-memory implementation of the DataClient interface for testing or local development.
repository: https://github.com/flutter-news-app-full-source-code/data-inmemory
publish_to: none
version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  data_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-client.git
      ref: v1.0.1
  logging: ^1.3.0

dev_dependencies:
  equatable: ^2.0.7
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^9.0.0
