name: data_inmemory
description: An in-memory implementation of the DataClient interface for testing or local development.
repository: https://github.com/flutter-news-app-full-source-code/data-inmemory
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 828b984517edec069266579c624c7af9fbe0e2ac
  data_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-client.git
      ref: 960a00882045ee252274d9d57bfca606c1fe5d64
  logging: ^1.3.0

dev_dependencies:
  equatable: ^2.0.7
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^9.0.0
